# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
#Importo libreria Numpy
import numpy as np

In [2]:
#Crear un arreglo de ceros de longitud 12
array_12=np.zeros((12))
array_12

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array_10=np.zeros((10))
array_10[9]=10
print(array_10)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]


In [9]:
# Crear un arreglo que tenga los números del 10 al 49
array_10_40=np.arange(10,50)
print(array_10_40)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

lista=[[0,1,2,3],[4,5,6,7]]
array30=np.array(lista)
print(array30)

[[0 1 2 3]
 [4 5 6 7]]


In [17]:
#Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
array100=np.random.randint(0,100,100)
print(array100)

[71 27 72  3 57 30 37 53 30  3 79 91 99 84 45 65 25  5 87  9 28 43 71 79
 11 92 81 96 98 71 86 13 45 32  7 42 69 80 72 40 44 93 85 20 79  1 83 92
  1 75 85 44 17 60 66 76 14  6 92 41 76 62 78 48 22 59 55 89 85 25 12 95
 56 14  6 98 97  4 21 48 90 11 65 91 67 41 50 24 84 36 73 58  8 10 69  3
  4 24 71 84]


In [18]:
#Calculo de media de array100
np.mean(array100)

52.15

In [19]:
#calculo de varianza de array100
np.var(array100
    )

961.7075

In [21]:
#Calcular la media de un arreglo usando np.sum

media_array100=np.sum(array100)/len(array100)

print(media_array100)

52.15


In [26]:
#Calcular la varianza de un arreglo usando np.sum y np.mean
var_array100=np.sum((array100-media_array100)**2/len(array100))
print(var_array100)

961.7074999999999


In [27]:
#Crear un array de números aleatorios usando np.random.randn.

array_aleatorio=np.random.rand(3,50,100)
print(array_aleatorio)

[[[0.45649737 0.89549589 0.62861231 ... 0.19611302 0.76443493 0.32536682]
  [0.28509343 0.55233447 0.96697768 ... 0.75325635 0.8718602  0.29018709]
  [0.94339262 0.44505964 0.61704753 ... 0.59181003 0.10804696 0.85696513]
  ...
  [0.67567984 0.03820761 0.64709013 ... 0.57628098 0.06813728 0.84187189]
  [0.16585475 0.90135212 0.10778952 ... 0.27646958 0.32390471 0.11207098]
  [0.8066444  0.08583077 0.06152955 ... 0.72703034 0.25518267 0.71168034]]

 [[0.17561963 0.75482888 0.49017338 ... 0.78063793 0.51746654 0.53060633]
  [0.04136394 0.81066254 0.83536136 ... 0.05935253 0.02439642 0.40495218]
  [0.79963765 0.21727415 0.65917321 ... 0.97003574 0.10059866 0.97076795]
  ...
  [0.14736252 0.17391253 0.70217844 ... 0.41992021 0.12601005 0.71867845]
  [0.47760226 0.97997216 0.3435456  ... 0.26083246 0.17280915 0.39437925]
  [0.75267944 0.83047516 0.03444759 ... 0.5237407  0.35612277 0.99778554]]

 [[0.51480539 0.86605232 0.83287473 ... 0.47118516 0.25102326 0.45095604]
  [0.5727721  0.419833